const defaultCryptos = [
    {
        name: "Bitcoin",
        symbol: "BTC",
        price: 28000,
        logo: "https://cryptologos.cc/logos/bitcoin-btc-logo.png",
        description: "Bitcoin est la première cryptomonnaie décentralisée qui permet des transactions pair à pair sans autorité centrale.",
    },
    {
        name: "Ethereum",
        symbol: "ETH",
        price: 1800,
        logo: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
        description: "Ethereum est une plateforme décentralisée qui permet de créer et d'exécuter des contrats intelligents et des applications décentralisées (dApps).",
    },
    {
        name: "Tether",
        symbol: "USDT",
        price: 1,
        logo: "https://cryptologos.cc/logos/tether-usdt-logo.png",
        description: "Tether est une cryptomonnaie stable qui suit la valeur du dollar américain.",
    },
    {
        name: "BNB",
        symbol: "BNB",
        price: 300,
        logo: "https://cryptologos.cc/logos/binance-coin-bnb-logo.png",
        description: "BNB est la cryptomonnaie native de Binance, utilisée pour réduire les frais de transaction et accéder à des fonctionnalités avancées.",
    },
    {
        name: "USD Coin",
        symbol: "USDC",
        price: 1,
        logo: "https://cryptologos.cc/logos/usd-coin-usdc-logo.png",
        description: "USD Coin est une autre cryptomonnaie stable, soutenue par des réserves en dollars.",
    },
    {
        name: "XRP",
        symbol: "XRP",
        price: 0.5,
        logo: "https://cryptologos.cc/logos/xrp-xrp-logo.png",
        description: "XRP est conçu pour les paiements numériques et les transferts d'argent transfrontaliers rapides.",
    },
    {
        name: "Cardano",
        symbol: "ADA",
        price: 0.4,
        logo: "https://cryptologos.cc/logos/cardano-ada-logo.png",
        description: "Cardano est une plateforme blockchain sécurisée qui vise à offrir des applications décentralisées.",
    },
    {
        name: "Dogecoin",
        symbol: "DOGE",
        price: 0.07,
        logo: "https://cryptologos.cc/logos/dogecoin-doge-logo.png",
        description: "Dogecoin est une cryptomonnaie créée comme une blague, mais elle est devenue populaire grâce à sa communauté.",
    },
    {
        name: "Solana",
        symbol: "SOL",
        price: 25,
        logo: "https://cryptologos.cc/logos/solana-sol-logo.png",
        description: "Solana est une blockchain rapide et évolutive pour les applications décentralisées.",
    },
    {
        name: "Polygon",
        symbol: "MATIC",
        price: 1.2,
        logo: "https://cryptologos.cc/logos/polygon-matic-logo.png",
        description: "Polygon est une solution de mise à l'échelle pour Ethereum, conçue pour améliorer les performances et réduire les frais.",
    },
];
